### ISSUE TITLE
Janusgraph 0.5.3 potential memory leak 

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#2524]
As noted in discussion, this PR potentially could be the cause of OOM when used with CQL storage backend: https://github.com/JanusGraph/janusgraph/pull/2080

- Version: 0.5.3
- Storage Backend: cql
- Mixed Index Backend: none
- Link to discussed bug: https://lists.lfaidata.foundation/g/janusgraph-users/topic/80139368
- Expected Behavior: No OOM
- Current Behavior: OOM
- Steps to Reproduce: https://gist.github.com/mad/df729c6a27a7ed224820cdd27209bade

**Comment by porunov** [comment]
I can reproduce OOM error even if I rollback #2080 , so possible we had this issue before

**Comment by li-boxuan** [comment]
If I am understanding it correctly, #2080 uncovers an existing problem (iterator leads to OOM). If that is the case, shouldn't we rollback #2080 if we cannot come up with a better solution as of now?

**Comment by li-boxuan** [comment]
By looking at the code, it seems the iterator version tries to do optimization by not eagerly allocating memory. This might work well for most of the cases because it does not require two entire copies of data (byte array and CQL resultSet) in memory. Instead, it uses a small guesstimation to allocate byte array initially and expands it when needed:

https://github.com/JanusGraph/janusgraph/blob/b00bfe7a4a4f3d936bd219cfe9858dbe18b5874d/janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntryList.java#L440-L445

However, the curse is, when you have a super large byte array, Doubling its size might create an OOM problem. Let's say we already have a 5G byte array, and we need to expand the byte array to suit the rest of the elements (might take only a few KB or MB if there are few elements left). The current naive algorithm doubles the byte array and makes it 10GB. This is far from optimal and could create an OOM problem that will probably not be observed in the iterable version, because it only takes as much space as it needs.

**Comment by rogaha** [comment]
the memory leak still exists on `master`. 

<img width="1468" alt="Screenshot of Safari (7-16-21, 12-45-24 AM)" src="https://user-images.githubusercontent.com/4483394/125888822-c02e6953-4eb5-4fb2-a5f0-79390ecd6596.png">

**Comment by li-boxuan** [comment]
@rogaha From your screenshot I cannot assure if it's a memory leak or not, due to the short period of time.  There can be other reasons, e.g. different workloads at different times during a day.

**Comment by porunov** [comment]
@rogaha Would you be able to build JanusGraph from this PR? #2700 I.e. https://github.com/porunov/janusgraph/tree/feature/cql-executor-service-configuration

And then add the next configurations to your configs:
```
storage.parallel-backend-executor-service.class = cached
storage.cql.executor-service.class = cached
```
You could potentially bump into the cql or parallel backend executors service limit which is fixed right now in `master` branch but we plan to make it configurable.
When using `cached` you won't have any hard limit. I don't say it's the reason you have problems but it could potentially be the reason.

**Comment by rogaha** [comment]
@porunov I'll git it a try and I let you know. thanks for working on it and for the help. I appreciate it.

**Comment by rogaha** [comment]
@porunov I’ve tried it, but it didn’t fix the issue, unfortunately. The memory still grows as new events are processed and suddenly the CPU spikes and the throughput drops. The time until this happens is related to the time janusgraph is in standby (no upsert queries).

**Comment by rogaha** [comment]
I’ve also tunned the connections per host limits (loca/remote). Local: 1->2 and remote: 1->10
