### ISSUE TITLE
Can't instantiate JanusGraph-HBase in Java

### ISSUE THREAD

**Issue by jbkoh** [JanusGraph/janusgraph#488]
### Configuration:
- Ubuntu 16.04
- Java 8
- Maven 3.3.9
- JanusGraph 0.1.1
- Eclipse Oxygen

### Code
```java
// Java
JanusGraph graph = JanusGraphFactory.open("conf/janusgraph-hbase.properties"); 
```

### Error Message
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsedTime(Ljava/util/concurrent/TimeUnit;)J
	at com.google.common.cache.LocalCache$LoadingValueReference.elapsedNanos(LocalCache.java:3600)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2407)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2373)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2335)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2250)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3985)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4788)
	at org.janusgraph.graphdb.transaction.vertexcache.GuavaVertexCache.get(GuavaVertexCache.java:83)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getInternalVertex(StandardJanusGraphTx.java:444)
	at org.janusgraph.graphdb.transaction.VertexIterable$1.nextVertex(VertexIterable.java:53)
	at org.janusgraph.graphdb.transaction.VertexIterable$1.<init>(VertexIterable.java:44)
	at org.janusgraph.graphdb.transaction.VertexIterable.iterator(VertexIterable.java:41)
	at com.google.common.collect.Iterables$6.iterator(Iterables.java:589)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$6.execute(StandardJanusGraphTx.java:1282)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$6.execute(StandardJanusGraphTx.java:1137)
	at org.janusgraph.graphdb.query.QueryProcessor$LimitAdjustingIterator.getNewIterator(QueryProcessor.java:209)
	at org.janusgraph.graphdb.query.LimitAdjustingIterator.hasNext(LimitAdjustingIterator.java:68)
	at com.google.common.collect.Iterators$8.computeNext(Iterators.java:686)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at org.janusgraph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:54)
	at org.janusgraph.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:44)
	at org.janusgraph.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:68)
	at com.google.common.collect.Iterables$7.iterator(Iterables.java:613)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$0(JanusGraphStep.java:69)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:136)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:42)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processAllStarts(ReducingBarrierStep.java:83)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processNextStart(ReducingBarrierStep.java:113)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:186)
	at metroinsight.citadel.metadata.impl.JanusgraphService.<init>(JanusgraphService.java:28)
	at metroinsight.citadel.metadata.impl.JanusgraphService.main(JanusgraphService.java:73)
```

### Other Notes
- The pom.xml is quite complicated with other projects, of which some are dependent to HBase.
- Regarding janusgraph, I have included "janusgraph-core", "janusgraph-hbase" in pom.xml
- I read a closed [issue](https://github.com/JanusGraph/janusgraph/issues/349) saying that I should place janusgraph-hbase earlier than guava in build path ordef, but somehow janusgraph-hbase does not show up in the build path (it's definitely included in pom.xml)

Could you help me to sort this out?

**Comment by jerryjch** [comment]
Does your project depend on Guava (other than from JanusGraph and HBase)?  What version of Guava (or multiple versions) in your final project or classpath?

**Comment by jbkoh** [comment]
Hi 

It does not directly depend on Guava, but it looks like added by some other dependencies. Its version is **12.0.1**. I also lowered that that class in the buildpath order, but it did not work.

**Comment by jerryjch** [comment]
JanusGraph needs a higher version of Guava (JanusGraph currently has 18.0).  The way it works for JanusGraph is that you should pull in Guava 18.0, and janusgraph-hbase bundles the deprecated StopWatch constructor so that the hbase part still works.

**Comment by pluradj** [comment]
This specific dependency order worked for me.

```
    <dependencies>
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-hbase</artifactId>
            <version>0.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-core</artifactId>
            <version>0.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-client</artifactId>
            <version>1.2.4</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.21</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

**Comment by jbkoh** [comment]
Thanks for the suggestions. I have reordered dependencies and now I see different error message with the same code. I see guava 18.0 from the build path.

### Error Message
```
0    [main] INFO  org.janusgraph.diskstorage.hbase.HBaseCompatLoader  - Instantiated HBase compatibility layer supporting runtime HBase version 1.2.6: org.janusgraph.diskstorage.hbase.HBaseCompat1_0
282  [main] INFO  org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Copied host list from root.storage.hostname to hbase.zookeeper.quorum: 127.0.0.1
369  [main] WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
974  [main] INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper  - Process identifier=hconnection-0x31f9b85e connecting to ZooKeeper ensemble=127.0.0.1:2181
981  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
981  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:host.name=jbkoh-Citadel
981  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:java.version=1.8.0_131
981  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:java.vendor=Oracle Corporation
981  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
981  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:java.class.path=/home/jbkoh/repo/citadel/target/classes:/home/jbkoh/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar:/home/jbkoh/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar:/home/jbkoh/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/home/jbkoh/.m2/repository/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar:/home/jbkoh/.m2/repository/org/janusgraph/janusgraph-core/0.1.1/janusgraph-core-0.1.1.jar:/home/jbkoh/.m2/repository/org/apache/tinkerpop/gremlin-core/3.2.3/gremlin-core-3.2.3.jar:/home/jbkoh/.m2/repository/org/apache/tinkerpop/gremlin-shaded/3.2.3/gremlin-shaded-3.2.3.jar:/home/jbkoh/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar:/home/jbkoh/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/jbkoh/.m2/repository/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar:/home/jbkoh/.m2/repository/org/javatuples/javatuples/1.2/javatuples-1.2.jar:/home/jbkoh/.m2/repository/com/carrotsearch/hppc/0.7.1/hppc-0.7.1.jar:/home/jbkoh/.m2/repository/com/jcabi/jcabi-manifests/1.1/jcabi-manifests-1.1.jar:/home/jbkoh/.m2/repository/com/jcabi/jcabi-log/0.14/jcabi-log-0.14.jar:/home/jbkoh/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar:/home/jbkoh/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar:/home/jbkoh/.m2/repository/org/apache/tinkerpop/gremlin-groovy/3.2.3/gremlin-groovy-3.2.3.jar:/home/jbkoh/.m2/repository/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7-indy.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy-groovysh/2.4.7/groovy-groovysh-2.4.7-indy.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7.jar:/home/jbkoh/.m2/repository/jline/jline/2.12/jline-2.12.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy-console/2.4.7/groovy-console-2.4.7.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy-swing/2.4.7/groovy-swing-2.4.7.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy-templates/2.4.7/groovy-templates-2.4.7.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy-xml/2.4.7/groovy-xml-2.4.7.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy-json/2.4.7/groovy-json-2.4.7-indy.jar:/home/jbkoh/.m2/repository/org/codehaus/groovy/groovy-jsr223/2.4.7/groovy-jsr223-2.4.7-indy.jar:/home/jbkoh/.m2/repository/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.jar:/home/jbkoh/.m2/repository/com/github/jeremyh/jBCrypt/jbcrypt-0.4/jBCrypt-jbcrypt-0.4.jar:/home/jbkoh/.m2/repository/org/apache/tinkerpop/tinkergraph-gremlin/3.2.3/tinkergraph-gremlin-3.2.3.jar:/home/jbkoh/.m2/repository/org/glassfish/javax.json/1.0/javax.json-1.0.jar:/home/jbkoh/.m2/repository/com/codahale/metrics/metrics-core/3.0.1/metrics-core-3.0.1.jar:/home/jbkoh/.m2/repository/com/codahale/metrics/metrics-ganglia/3.0.1/metrics-ganglia-3.0.1.jar:/home/jbkoh/.m2/repository/info/ganglia/gmetric4j/gmetric4j/1.0.3/gmetric4j-1.0.3.jar:/home/jbkoh/.m2/repository/com/codahale/metrics/metrics-graphite/3.0.1/metrics-graphite-3.0.1.jar:/home/jbkoh/.m2/repository/org/reflections/reflections/0.9.9-RC1/reflections-0.9.9-RC1.jar:/home/jbkoh/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/home/jbkoh/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar:/home/jbkoh/.m2/repository/org/javassist/javassist/3.16.1-GA/javassist-3.16.1-GA.jar:/home/jbkoh/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar:/home/jbkoh/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar:/home/jbkoh/.m2/repository/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.jar:/home/jbkoh/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/home/jbkoh/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/jbkoh/.m2/repository/commons-io/commons-io/2.3/commons-io-2.3.jar:/home/jbkoh/.m2/repository/commons-codec/commons-codec/1.7/commons-codec-1.7.jar:/home/jbkoh/.m2/repository/com/github/stephenc/high-scale-lib/high-scale-lib/1.1.4/high-scale-lib-1.1.4.jar:/home/jbkoh/.m2/repository/org/janusgraph/janusgraph-hbase/0.1.1/janusgraph-hbase-0.1.1.jar:/home/jbkoh/.m2/repository/org/slf4j/slf4j-log4j12/1.7.12/slf4j-log4j12-1.7.12.jar:/home/jbkoh/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar:/home/jbkoh/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar:/home/jbkoh/.m2/repository/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar:/home/jbkoh/.m2/repository/org/apache/hbase/hbase-client/1.2.6/hbase-client-1.2.6.jar:/home/jbkoh/.m2/repository/org/apache/hbase/hbase-annotations/1.2.6/hbase-annotations-1.2.6.jar:/home/jbkoh/.m2/repository/com/github/stephenc/findbugs/findbugs-annotations/1.3.9-1/findbugs-annotations-1.3.9-1.jar:/home/jbkoh/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/jbkoh/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/jbkoh/.m2/repository/org/apache/hbase/hbase-common/1.2.6/hbase-common-1.2.6.jar:/home/jbkoh/.m2/repository/org/apache/hbase/hbase-protocol/1.2.6/hbase-protocol-1.2.6.jar:/home/jbkoh/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar:/home/jbkoh/.m2/repository/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar:/home/jbkoh/.m2/repository/org/apache/htrace/htrace-core/3.1.0-incubating/htrace-core-3.1.0-incubating.jar:/home/jbkoh/.m2/repository/org/apache/hadoop/hadoop-common/2.5.1/hadoop-common-2.5.1.jar:/home/jbkoh/.m2/repository/org/apache/hadoop/hadoop-annotations/2.5.1/hadoop-annotations-2.5.1.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar:/home/jbkoh/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar:/home/jbkoh/.m2/repository/org/apache/commons/commons-math3/3.1.1/commons-math3-3.1.1.jar:/home/jbkoh/.m2/repository/xmlenc/xmlenc/0.52/xmlenc-0.52.jar:/home/jbkoh/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar:/home/jbkoh/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar:/home/jbkoh/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar:/home/jbkoh/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar:/home/jbkoh/.m2/repository/commons-el/commons-el/1.0/commons-el-1.0.jar:/home/jbkoh/.m2/repository/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar:/home/jbkoh/.m2/repository/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.jar:/home/jbkoh/.m2/repository/org/apache/avro/avro/1.7.4/avro-1.7.4.jar:/home/jbkoh/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar:/home/jbkoh/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar:/home/jbkoh/.m2/repository/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar:/home/jbkoh/.m2/repository/org/tukaani/xz/1.0/xz-1.0.jar:/home/jbkoh/.m2/repository/org/apache/hadoop/hadoop-auth/2.5.1/hadoop-auth-2.5.1.jar:/home/jbkoh/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar:/home/jbkoh/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar:/home/jbkoh/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar:/home/jbkoh/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar:/home/jbkoh/.m2/repository/com/jcraft/jsch/0.1.42/jsch-0.1.42.jar:/home/jbkoh/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar:/home/jbkoh/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-core/2.5.1/hadoop-mapreduce-client-core-2.5.1.jar:/home/jbkoh/.m2/repository/org/apache/hadoop/hadoop-yarn-common/2.5.1/hadoop-yarn-common-2.5.1.jar:/home/jbkoh/.m2/repository/org/apache/hadoop/hadoop-yarn-api/2.5.1/hadoop-yarn-api-2.5.1.jar:/home/jbkoh/.m2/repository/org/jruby/jcodings/jcodings/1.0.8/jcodings-1.0.8.jar:/home/jbkoh/.m2/repository/org/jruby/joni/joni/2.1.2/joni-2.1.2.jar:/home/jbkoh/.m2/repository/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar:/home/jbkoh/.m2/repository/org/locationtech/geomesa/geomesa-hbase-datastore_2.11/1.3.1/geomesa-hbase-datastore_2.11-1.3.1.jar:/home/jbkoh/.m2/repository/org/locationtech/geomesa/geomesa-index-api_2.11/1.3.1/geomesa-index-api_2.11-1.3.1.jar:/home/jbkoh/.m2/repository/org/locationtech/geomesa/geomesa-filter_2.11/1.3.1/geomesa-filter_2.11-1.3.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-main/15.1/gt-main-15.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-api/15.1/gt-api-15.1.jar:/home/jbkoh/.m2/repository/com/vividsolutions/jts/1.13/jts-1.13.jar:/home/jbkoh/.m2/repository/org/geotools/gt-referencing/15.1/gt-referencing-15.1.jar:/home/jbkoh/.m2/repository/com/googlecode/efficient-java-matrix-library/core/0.26/core-0.26.jar:/home/jbkoh/.m2/repository/commons-pool/commons-pool/1.5.4/commons-pool-1.5.4.jar:/home/jbkoh/.m2/repository/org/geotools/gt-metadata/15.1/gt-metadata-15.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-opengis/15.1/gt-opengis-15.1.jar:/home/jbkoh/.m2/repository/net/java/dev/jsr-275/jsr-275/1.0-beta-2/jsr-275-1.0-beta-2.jar:/home/jbkoh/.m2/repository/jgridshift/jgridshift/1.0/jgridshift-1.0.jar:/home/jbkoh/.m2/repository/net/sf/geographiclib/GeographicLib-Java/1.44/GeographicLib-Java-1.44.jar:/home/jbkoh/.m2/repository/org/jdom/jdom/1.1.3/jdom-1.1.3.jar:/home/jbkoh/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar:/home/jbkoh/.m2/repository/org/joda/joda-convert/1.6/joda-convert-1.6.jar:/home/jbkoh/.m2/repository/org/geotools/gt-cql/15.1/gt-cql-15.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-transform/15.1/gt-transform-15.1.jar:/home/jbkoh/.m2/repository/org/locationtech/geomesa/geomesa-utils_2.11/1.3.1/geomesa-utils_2.11-1.3.1.jar:/home/jbkoh/.m2/repository/org/locationtech/geomesa/geomesa-logger_2.11/1.3.1/geomesa-logger_2.11-1.3.1.jar:/home/jbkoh/.m2/repository/com/typesafe/scala-logging/scala-logging_2.11/3.1.0/scala-logging_2.11-3.1.0.jar:/home/jbkoh/.m2/repository/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar:/home/jbkoh/.m2/repository/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar:/home/jbkoh/.m2/repository/org/locationtech/geomesa/geomesa-z3_2.11/1.3.1/geomesa-z3_2.11-1.3.1.jar:/home/jbkoh/.m2/repository/org/locationtech/sfcurve/sfcurve-zorder_2.11/0.2.0/sfcurve-zorder_2.11-0.2.0.jar:/home/jbkoh/.m2/repository/org/locationtech/sfcurve/sfcurve-api_2.11/0.2.0/sfcurve-api_2.11-0.2.0.jar:/home/jbkoh/.m2/repository/org/apache/commons/commons-pool2/2.2/commons-pool2-2.2.jar:/home/jbkoh/.m2/repository/org/apache/commons/commons-csv/1.0/commons-csv-1.0.jar:/home/jbkoh/.m2/repository/org/geotools/gt-grid/15.1/gt-grid-15.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-data/15.1/gt-data-15.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-shapefile/15.1/gt-shapefile-15.1.jar:/home/jbkoh/.m2/repository/org/locationtech/spatial4j/spatial4j/0.6/spatial4j-0.6.jar:/home/jbkoh/.m2/repository/com/typesafe/config/1.2.1/config-1.2.1.jar:/home/jbkoh/.m2/repository/com/esotericsoftware/kryo/kryo/2.21/kryo-2.21.jar:/home/jbkoh/.m2/repository/com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07-shaded.jar:/home/jbkoh/.m2/repository/com/esotericsoftware/minlog/minlog/1.2/minlog-1.2.jar:/home/jbkoh/.m2/repository/org/objenesis/objenesis/1.2/objenesis-1.2.jar:/home/jbkoh/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar:/home/jbkoh/.m2/repository/com/clearspring/analytics/stream/2.9.2/stream-2.9.2.jar:/home/jbkoh/.m2/repository/org/parboiled/parboiled-scala_2.11/1.1.7/parboiled-scala_2.11-1.1.7.jar:/home/jbkoh/.m2/repository/org/parboiled/parboiled-core/1.1.7/parboiled-core-1.1.7.jar:/home/jbkoh/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.5/scala-parser-combinators_2.11-1.0.5.jar:/home/jbkoh/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.5/scala-xml_2.11-1.0.5.jar:/home/jbkoh/.m2/repository/org/locationtech/geomesa/geomesa-feature-kryo_2.11/1.3.1/geomesa-feature-kryo_2.11-1.3.1.jar:/home/jbkoh/.m2/repository/org/locationtech/geomesa/geomesa-feature-common_2.11/1.3.1/geomesa-feature-common_2.11-1.3.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-process-feature/15.1/gt-process-feature-15.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-process/15.1/gt-process-15.1.jar:/home/jbkoh/.m2/repository/org/geotools/gt-coverage/15.1/gt-coverage-15.1.jar:/home/jbkoh/.m2/repository/it/geosolutions/imageio-ext/imageio-ext-tiff/1.1.15/imageio-ext-tiff-1.1.15.jar:/home/jbkoh/.m2/repository/it/geosolutions/imageio-ext/imageio-ext-utilities/1.1.15/imageio-ext-utilities-1.1.15.jar:/home/jbkoh/.m2/repository/it/geosolutions/imageio-ext/imageio-ext-geocore/1.1.15/imageio-ext-geocore-1.1.15.jar:/home/jbkoh/.m2/repository/it/geosolutions/imageio-ext/imageio-ext-streams/1.1.15/imageio-ext-streams-1.1.15.jar:/home/jbkoh/.m2/repository/org/jaitools/jt-zonalstats/1.4.0/jt-zonalstats-1.4.0.jar:/home/jbkoh/.m2/repository/org/jaitools/jt-utils/1.4.0/jt-utils-1.4.0.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/affine/jt-affine/1.0.9/jt-affine-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/iterators/jt-iterators/1.0.9/jt-iterators-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/utilities/jt-utilities/1.0.9/jt-utilities-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/scale/jt-scale/1.0.9/jt-scale-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/translate/jt-translate/1.0.9/jt-translate-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/algebra/jt-algebra/1.0.9/jt-algebra-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/bandmerge/jt-bandmerge/1.0.9/jt-bandmerge-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/bandselect/jt-bandselect/1.0.9/jt-bandselect-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/bandcombine/jt-bandcombine/1.0.9/jt-bandcombine-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/border/jt-border/1.0.9/jt-border-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/buffer/jt-buffer/1.0.9/jt-buffer-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/crop/jt-crop/1.0.9/jt-crop-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/mosaic/jt-mosaic/1.0.9/jt-mosaic-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/lookup/jt-lookup/1.0.9/jt-lookup-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/nullop/jt-nullop/1.0.9/jt-nullop-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/rescale/jt-rescale/1.0.9/jt-rescale-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/stats/jt-stats/1.0.9/jt-stats-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/warp/jt-warp/1.0.9/jt-warp-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/zonal/jt-zonal/1.0.9/jt-zonal-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/binarize/jt-binarize/1.0.9/jt-binarize-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/format/jt-format/1.0.9/jt-format-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/colorconvert/jt-colorconvert/1.0.9/jt-colorconvert-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/errordiffusion/jt-errordiffusion/1.0.9/jt-errordiffusion-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/orderdither/jt-orderdither/1.0.9/jt-orderdither-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/colorindexer/jt-colorindexer/1.0.9/jt-colorindexer-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/imagefunction/jt-imagefunction/1.0.9/jt-imagefunction-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/piecewise/jt-piecewise/1.0.9/jt-piecewise-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/classifier/jt-classifier/1.0.9/jt-classifier-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/rlookup/jt-rlookup/1.0.9/jt-rlookup-1.0.9.jar:/home/jbkoh/.m2/repository/it/geosolutions/jaiext/vectorbin/jt-vectorbin/1.0.9/jt-vectorbin-1.0.9.jar:/home/jbkoh/.m2/repository/org/json4s/json4s-native_2.11/3.2.10/json4s-native_2.11-3.2.10.jar:/home/jbkoh/.m2/repository/org/json4s/json4s-core_2.11/3.2.10/json4s-core_2.11-3.2.10.jar:/home/jbkoh/.m2/repository/org/json4s/json4s-ast_2.11/3.2.10/json4s-ast_2.11-3.2.10.jar:/home/jbkoh/.m2/repository/org/scala-lang/scalap/2.11.0/scalap-2.11.0.jar:/home/jbkoh/.m2/repository/org/scala-lang/scala-compiler/2.11.0/scala-compiler-2.11.0.jar:/home/jbkoh/.m2/repository/com/jayway/jsonpath/json-path/2.2.0/json-path-2.2.0.jar:/home/jbkoh/.m2/repository/net/minidev/json-smart/2.2.1/json-smart-2.2.1.jar:/home/jbkoh/.m2/repository/net/minidev/accessors-smart/1.1/accessors-smart-1.1.jar:/home/jbkoh/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.3.3/caffeine-2.3.3.jar:/home/jbkoh/.m2/repository/org/calrissian/mango/mango-core/1.2.0/mango-core-1.2.0.jar:/home/jbkoh/.m2/repository/org/geotools/gt-epsg-hsql/15.1/gt-epsg-hsql-15.1.jar:/home/jbkoh/.m2/repository/org/hsqldb/hsqldb/2.3.0/hsqldb-2.3.0.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-core/3.4.1/vertx-core-3.4.1.jar:/home/jbkoh/.m2/repository/io/netty/netty-common/4.1.8.Final/netty-common-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-buffer/4.1.8.Final/netty-buffer-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-transport/4.1.8.Final/netty-transport-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-resolver/4.1.8.Final/netty-resolver-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-handler/4.1.8.Final/netty-handler-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-codec/4.1.8.Final/netty-codec-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-handler-proxy/4.1.8.Final/netty-handler-proxy-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-codec-socks/4.1.8.Final/netty-codec-socks-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-codec-http/4.1.8.Final/netty-codec-http-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-codec-http2/4.1.8.Final/netty-codec-http2-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-resolver-dns/4.1.8.Final/netty-resolver-dns-4.1.8.Final.jar:/home/jbkoh/.m2/repository/io/netty/netty-codec-dns/4.1.8.Final/netty-codec-dns-4.1.8.Final.jar:/home/jbkoh/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.7.4/jackson-core-2.7.4.jar:/home/jbkoh/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.7.4/jackson-databind-2.7.4.jar:/home/jbkoh/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.7.0/jackson-annotations-2.7.0.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-unit/3.4.1/vertx-unit-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-web/3.4.1/vertx-web-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-auth-common/3.4.1/vertx-auth-common-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-mongo-client/3.4.1/vertx-mongo-client-3.4.1.jar:/home/jbkoh/.m2/repository/org/mongodb/mongodb-driver-async/3.4.1/mongodb-driver-async-3.4.1.jar:/home/jbkoh/.m2/repository/org/mongodb/mongodb-driver-core/3.4.1/mongodb-driver-core-3.4.1.jar:/home/jbkoh/.m2/repository/org/mongodb/bson/3.4.1/bson-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-rx-java/3.4.1/vertx-rx-java-3.4.1.jar:/home/jbkoh/.m2/repository/io/reactivex/rxjava/1.2.7/rxjava-1.2.7.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-config/3.4.1/vertx-config-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-codegen/3.4.1/vertx-codegen-3.4.1.jar:/home/jbkoh/.m2/repository/org/mvel/mvel2/2.2.8.Final/mvel2-2.2.8.Final.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-service-proxy/3.4.1/vertx-service-proxy-3.4.1-processor.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-lang-js/3.4.1/vertx-lang-js-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-service-discovery/3.4.1/vertx-service-discovery-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-web-client/3.4.1/vertx-web-client-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-web-common/3.4.1/vertx-web-common-3.4.1.jar:/home/jbkoh/.m2/repository/io/vertx/vertx-redis-client/3.4.2/vertx-redis-client-3.4.2.jar:/home/jbkoh/.m2/repository/de/flapdoodle/embed/de.flapdoodle.embed.mongo/1.50.0/de.flapdoodle.embed.mongo-1.50.0.jar:/home/jbkoh/.m2/repository/de/flapdoodle/embed/de.flapdoodle.embed.process/1.50.0/de.flapdoodle.embed.process-1.50.0.jar:/home/jbkoh/.m2/repository/net/java/dev/jna/jna/4.0.0/jna-4.0.0.jar:/home/jbkoh/.m2/repository/net/java/dev/jna/jna-platform/4.0.0/jna-platform-4.0.0.jar:/home/jbkoh/.m2/repository/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar
982  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
983  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:java.io.tmpdir=/tmp
983  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:java.compiler=<NA>
983  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:os.name=Linux
983  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:os.arch=amd64
983  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:os.version=4.10.0-33-generic
983  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:user.name=jbkoh
983  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:user.home=/home/jbkoh
983  [main] INFO  org.apache.zookeeper.ZooKeeper  - Client environment:user.dir=/home/jbkoh/repo/citadel
984  [main] INFO  org.apache.zookeeper.ZooKeeper  - Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=90000 watcher=hconnection-0x31f9b85e0x0, quorum=127.0.0.1:2181, baseZNode=/hbase
1006 [main-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn  - Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
1018 [main-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn  - Socket connection established to 127.0.0.1/127.0.0.1:2181, initiating session
1033 [main-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn  - Session establishment complete on server 127.0.0.1/127.0.0.1:2181, sessionid = 0x15e40e20044000b, negotiated timeout = 40000
1376 [main] WARN  org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Unexpected exception during getDeployment()
java.lang.RuntimeException: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:354)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:393)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1354)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:75)
	at metroinsight.citadel.metadata.impl.JanusgraphService.<init>(JanusgraphService.java:26)
	at metroinsight.citadel.metadata.impl.JanusgraphService.main(JanusgraphService.java:73)
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:755)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getLocalKeyPartition(HBaseStoreManager.java:557)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:351)
	... 6 more
Caused by: org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:239)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:212)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:327)
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:302)
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:167)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:162)
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:797)
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:602)
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:366)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:406)
	at org.janusgraph.diskstorage.hbase.HBaseAdmin1_0.tableExists(HBaseAdmin1_0.java:77)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:749)
	... 8 more
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:604)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:588)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:561)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1211)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1178)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:305)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:156)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
	... 18 more
1383 [main] WARN  org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Unexpected exception during getDeployment()
java.lang.RuntimeException: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:354)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:393)
	at org.janusgraph.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:442)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1355)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:75)
	at metroinsight.citadel.metadata.impl.JanusgraphService.<init>(JanusgraphService.java:26)
	at metroinsight.citadel.metadata.impl.JanusgraphService.main(JanusgraphService.java:73)
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:755)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getLocalKeyPartition(HBaseStoreManager.java:557)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:351)
	... 7 more
Caused by: org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:239)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:212)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:327)
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:302)
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:167)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:162)
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:797)
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:602)
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:366)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:406)
	at org.janusgraph.diskstorage.hbase.HBaseAdmin1_0.tableExists(HBaseAdmin1_0.java:77)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:749)
	... 9 more
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:604)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:588)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:561)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1211)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1178)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:305)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:156)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
	... 19 more
1416 [main] WARN  org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Unexpected exception during getDeployment()
java.lang.RuntimeException: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:354)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:393)
	at org.janusgraph.diskstorage.common.AbstractStoreManager.getMetaDataSchema(AbstractStoreManager.java:58)
	at org.janusgraph.diskstorage.hbase.HBaseKeyColumnValueStore.<init>(HBaseKeyColumnValueStore.java:81)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.openDatabase(HBaseStoreManager.java:450)
	at org.janusgraph.diskstorage.keycolumnvalue.KeyColumnValueStoreManager.openDatabase(KeyColumnValueStoreManager.java:43)
	at org.janusgraph.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:453)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1355)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:75)
	at metroinsight.citadel.metadata.impl.JanusgraphService.<init>(JanusgraphService.java:26)
	at metroinsight.citadel.metadata.impl.JanusgraphService.main(JanusgraphService.java:73)
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:755)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getLocalKeyPartition(HBaseStoreManager.java:557)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:351)
	... 11 more
Caused by: org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:239)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:212)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:327)
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:302)
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:167)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:162)
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:797)
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:602)
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:366)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:406)
	at org.janusgraph.diskstorage.hbase.HBaseAdmin1_0.tableExists(HBaseAdmin1_0.java:77)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:749)
	... 13 more
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:604)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:588)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:561)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1211)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1178)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:305)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:156)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
	... 23 more
Exception in thread "main" org.janusgraph.core.JanusGraphException: Could not open global configuration
	at org.janusgraph.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:455)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1355)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:75)
	at metroinsight.citadel.metadata.impl.JanusgraphService.<init>(JanusgraphService.java:26)
	at metroinsight.citadel.metadata.impl.JanusgraphService.main(JanusgraphService.java:73)
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:755)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureColumnFamilyExists(HBaseStoreManager.java:827)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.openDatabase(HBaseStoreManager.java:460)
	at org.janusgraph.diskstorage.keycolumnvalue.KeyColumnValueStoreManager.openDatabase(KeyColumnValueStoreManager.java:43)
	at org.janusgraph.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:453)
	... 5 more
Caused by: org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:239)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:212)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:327)
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:302)
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:167)
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:162)
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:797)
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:602)
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:366)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:406)
	at org.janusgraph.diskstorage.hbase.HBaseAdmin1_0.tableExists(HBaseAdmin1_0.java:77)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:749)
	... 9 more
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:604)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:588)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:561)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1211)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1178)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:305)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:156)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
	... 19 more
```

### Dependency Tree
I wanted to find where the guava conflict happens so I did dependency tree analysis [link](https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html)
```bash
mvn dependency:tree -Dverbose -Dincludes=guava
```

However, it did not show anything but like this:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Citadel 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ Citadel ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.737 s
[INFO] Finished at: 2017-09-02T00:31:31-07:00
[INFO] Final Memory: 30M/347M
[INFO] ------------------------------------------------------------------------
```

Maybe the package name used there is wrong, but it's my current observation.

Is there any further suggestions? Thank you!

**Comment by pluradj** [comment]
What are the dependencies in your pom.xml? What I pasted previously works with this example.
https://github.com/pluradj/janusgraph-java-example

**Comment by jerryjch** [comment]
You hit #349 now.  See the comments there.
The Guava case is a messy case. We have to work on using the [shaded hbase client](https://issues.apache.org/jira/browse/HBASE-13517) and providing shaded JanusGraph.

**Comment by jbkoh** [comment]
Thanks a ton, both of you. I misread #349 to put guava first. I put janusgraph-hbase first and it works. Thanks!

**Comment by ramjaddu** [comment]
Hi ,

It seems, problem comes from dependent libraries,

basically you will get the problem when your trying to put the data into hbase table.

initially I had used <dependency> <groupId>org.apache.hbase</groupId> <artifactId>hbase-client</artifactId> <version>1.1.2</version> </dependency>

i got the similar problem and later I changed to

<dependency> <groupId>org.apache.hbase</groupId> <artifactId>hbase-shaded-client</artifactId> <version>1.1.2</version> </dependency>

now the problem has been resolved.

Regards,

Ram.

**Comment by wtt1027** [comment]
> Thanks a ton, both of you. I misread #349 to put guava first. I put janusgraph-hbase first and it works. Thanks!

I encountered the same problem with version 0.5.2, how did you solve it?

**Comment by wtt1027** [comment]
> Hi ,
> 
> It seems, problem comes from dependent libraries,
> 
> basically you will get the problem when your trying to put the data into hbase table.
> 
> initially I had used org.apache.hbase hbase-client 1.1.2
> 
> i got the similar problem and later I changed to
> 
> org.apache.hbase hbase-shaded-client 1.1.2
> 
> now the problem has been resolved.
> 
> Regards,
> 
> Ram.

I had used org.apache.hbase hbase-client 2.1.5 and I changed to

org.apache.hbase hbase-shaded-client 2.1.5 The problem is not solved
